// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository_sqlc

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg *CreateEventParams) error
	CreateOrder(ctx context.Context, userID int64) (int64, error)
	CreateOrderItems(ctx context.Context, arg *CreateOrderItemsParams) error
	FetchNextMessages(ctx context.Context, limit int32) ([]*FetchNextMessagesRow, error)
	GetByOrderID(ctx context.Context, id int64) ([]*GetByOrderIDRow, error)
	GetByOrderIDForUpdate(ctx context.Context, id int64) ([]*GetByOrderIDForUpdateRow, error)
	GetStockBySku(ctx context.Context, sku int64) (*GetStockBySkuRow, error)
	GetStocksBySkuForUpdate(ctx context.Context, sku []int64) ([]*GetStocksBySkuForUpdateRow, error)
	MarkAsError(ctx context.Context, ids []int64) error
	MarkAsSent(ctx context.Context, ids []int64) error
	SetStatus(ctx context.Context, arg *SetStatusParams) error
	UpdateStocks(ctx context.Context, arg *UpdateStocksParams) error
}

var _ Querier = (*Queries)(nil)
