{
 "title": "cart",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Количество запросов в секунду (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(cart_http_request_total{path=\"/metrics\"}[10m]))by(status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Гистограмма задержки времени ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(cart_http_request_duration_seconds_bucket{}[1m]))by(le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество объектов в In-Memory репозитории",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(cart_storage_items_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}