{
 "title": "loms",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Количество gRPC запросов в секунду (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(loms_grpc_request_total{}[10m]))by(path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Гистограмма задержки времени gRPC  ответа ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loms_grpc_request_duration_seconds_bucket{}[1m]))by(le, path))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество запросов к базе данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(loms_db_query_total{}[10m]))by(category, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Гистограмма задержки ответов от базы данных",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(loms_db_query_duration_seconds_bucket{}[10m]))by(category, status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}